
Enum "financials_unit_enum" {
  "Units"
  "Thousands"
  "Millions"
  "Billions"
}

Table "actors" {
  "actor_id" int [pk, not null, increment]
  "name" varchar(45) [not null]
  "birth_year" year [default: NULL]
}

Table "financials" {
  "movie_id" int [pk, not null]
  "budget" decimal(10,2) [default: NULL]
  "revenue" decimal(10,2) [default: NULL]
  "unit" financials_unit_enum [default: NULL]
  "currency" char(3) [default: NULL]
}

Table "languages" {
  "language_id" tinyint [pk, not null, increment]
  "name" varchar(45) [not null]

  Indexes {
    name [unique, name: "name_UNIQUE"]
  }
}

Table "movie_actor" {
  "movie_id" int [not null]
  "actor_id" int [not null]

  Indexes {
    (movie_id, actor_id) [pk]
    movie_id [name: "fk_movie_actor_movies_idx"]
    actor_id [name: "fk_movie_actor_actors_idx"]
  }
}

Table "movies" {
  "movie_id" int [pk, not null, increment]
  "title" varchar(150) [not null]
  "industry" varchar(45) [default: NULL]
  "release_year" year [default: NULL]
  "imdb_rating" decimal(3,1) [default: NULL]
  "studio" varchar(45) [default: NULL]
  "language_id" tinyint [default: NULL]

  Indexes {
    language_id [name: "fk_movies_languages_idx"]
  }
}

Ref "fk_movie_actor_actors":"actors"."actor_id" < "movie_actor"."actor_id" [update: cascade, delete: restrict]

Ref "fk_movie_actor_movies":"movies"."movie_id" < "movie_actor"."movie_id" [update: cascade, delete: restrict]

Ref "fk_movies_languages":"languages"."language_id" < "movies"."language_id" [update: cascade, delete: restrict]

